### ISSUE TITLE
API token

### ISSUE THREAD

**Issue by plentia** [azogue/ha-pvpc-custom#9]
Hi.

Just a stupid question:
Once installed from HACS, where can I put my personal API token? In which file?

Thanks for your time a kind regards.

**Comment by azogue** [comment]
Hi @plentia,

> In which file?

You don't have to edit anything. The custom component works like the official integration: you need to configure it from 'Integrations' ("Spain electricity hourly pricing (PVPC)"), and then follow the config-flow, checking on "Enable Esios API Token" 😜

<img width="400" alt="ha-pvpc-configure-1" src="https://github.com/azogue/ha-pvpc-custom/assets/9748301/37cd73d9-8667-4c5d-a22d-402f6588294c">

<img width="602" alt="ha-pvpc-configure-2" src="https://github.com/azogue/ha-pvpc-custom/assets/9748301/6f7d8cbd-d43e-45c2-810d-717fd72951b6">
